import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useReducer,
  useRef,
  type ReactNode,
} from "react";
import type {
  CanonicalSectionId,
  ExtractionResult,
  ExtractionStatus,
  FollowUpMemo,
  FullResearchReportState,
  ResearchReportSectionId,
  ResearchReportSection,
  ResearchReportSectionRunState,
  LlmGenerationErrorCode,
  LlmGenerationState,
  LlmGenerationWarning,
  LlmStatusResponse,
  LocalUploadedFile,
  MemoDNA,
  MemoGenerationProgress,
  MemoSection,
  MemoUnderstanding,
  MemoUnderstandErrorCode,
  MemoUnderstandingState,
  PeriodDetectionResult,
  ResearchErrorCode,
  ResearchFindings,
  ResearchGenerationState,
  ResearchPassId,
  ResearchPassRunState,
  PrioritiesAnswerState,
  ResearchProgress,
  SectionRunState,
  SelectedCompany,
} from "@shared/types";
import { api } from "../lib/api";
import { extractText } from "../lib/extract";
import {
  extractionSupported,
  getExtension,
  mimeForFile,
} from "../lib/fileMeta";
import { buildMemoDnaFromText } from "../lib/memoDna";
import { detectPeriodFromMemoText } from "../lib/periodDetect";
import {
  computeMemoCoverage,
  detectMemoWrittenOn,
  parseFreeFormDateToIso,
  type MemoCoverageSignals,
} from "../lib/memoAnalysis";
import {
  CANONICAL_SECTION_IDS,
  SECTION_TITLES,
  runSectionGeneration,
} from "../lib/sectionGeneration";
import {
  RESEARCH_PASS_IDS,
  RESEARCH_PASS_TITLES,
  detectionToResearchDetectionInput,
} from "../lib/researchPasses";
import { buildMemoUnderstandingDigest } from "../lib/memoUnderstandingSummary";
import { fetchCurrentPrice } from "../lib/livePrice";
import { getLlmGateToken } from "../lib/llmGateToken";
import { APP_BUILD_ID } from "@shared/buildId";
import {
  RESEARCH_REPORT_SECTION_ORDER,
  RESEARCH_REPORT_SECTION_TITLES,
} from "@shared/researchReport";
import { runFullResearchReport } from "../lib/researchReport";

const GATE_TOKEN_POLL_KEY = "memo.llm.gate";

export interface PeriodOverride {
  detectedCompany?: string;
  periodLabel?: string;
  researchStart?: string;
}

interface State {
  // The company the user picked from the search box BEFORE uploading. This
  // is the authoritative project identity — it overrides the heuristic
  // company/ticker that period detection guesses from the memo body (which
  // can latch onto a segment line-item, e.g. "Lloyd Electric" in a Havells
  // report). null until a company is selected; the upload slot stays gated
  // until then.
  selectedCompany: SelectedCompany | null;
  initialFile: LocalUploadedFile | null;
  extraction: ExtractionResult | null;
  extractionStatus: ExtractionStatus;
  dna: MemoDNA | null;
  detection: PeriodDetectionResult | null;
  // Coverage signals computed deterministically from the extracted text the
  // moment the memo is uploaded. Drives "skip the Shareholding section if
  // the memo never mentioned shareholding" — the user's explicit ask: the
  // follow-up memo should only contain what the original memo covered.
  memoCoverage: MemoCoverageSignals | null;
  periodOverride: PeriodOverride;
  research: ResearchFindings | null;
  researchState: ResearchGenerationState;
  researchProgress: ResearchProgress;
  // Stage 1 of the research rearchitecture: the comprehensive, company-wide
  // research report (kept internally, condensed into the memo in Stage 2, and
  // used to answer follow-up Q&A in Stage 3). Additive for now — it does not
  // yet feed memo generation.
  fullReport: FullResearchReportState;
  fullReportProgress: ResearchReportSectionRunState[];
  generatedMemo: FollowUpMemo | null;
  llm: LlmGenerationState;
  // Dashboard-only priorities Q&A — never enters the downloadable memo.
  // Generated by /api/generate/priorities-answer right after the memo
  // succeeds, IF the user typed anything into the priorities textarea.
  prioritiesAnswer: PrioritiesAnswerState;
  progress: MemoGenerationProgress;
  completedSections: Partial<Record<CanonicalSectionId, MemoSection>>;
  llmProviderStatus: LlmStatusResponse | null;
  demoFollowUpMemo: FollowUpMemo | null;
  gateTokenSet: boolean;
  // Phase 6A: Memo Understanding Engine state.
  understanding: MemoUnderstandingState;
  // Emergency / developer-only escape: when true, the Research button
  // skips the requirement that memoUnderstanding succeed first. Surfaced
  // only inside a <details> disclosure in MemoUnderstandingCard.
  skipUnderstanding: boolean;
  // Phase 6C: free-text the user typed into the "What else should we
  // test?" priorities textbox. Threaded into every research pass and
  // every memo section so the memo addresses what the user asked.
  userResearchPriorities: string;
  // Phase 6H: true when this browser bundle's build id no longer matches
  // the deployed worker's (a stale tab). Drives a reload banner so the
  // user never hits cryptic "stale_client" 400s mid-generation.
  staleClient: boolean;
}

type Action =
  | { type: "SET_SELECTED_COMPANY"; company: SelectedCompany }
  | { type: "CLEAR_SELECTED_COMPANY" }
  | { type: "SET_INITIAL_FILE"; file: LocalUploadedFile | null }
  | { type: "SET_EXTRACTION_STATUS"; status: ExtractionStatus }
  | { type: "SET_EXTRACTION"; result: ExtractionResult }
  | {
      type: "SET_DNA_AND_DETECTION";
      dna: MemoDNA;
      detection: PeriodDetectionResult;
      coverage: MemoCoverageSignals;
    }
  | { type: "SET_PERIOD_OVERRIDE"; override: PeriodOverride }
  | { type: "SET_RESEARCH_STATE"; state: ResearchGenerationState }
  | { type: "SET_RESEARCH"; research: ResearchFindings | null }
  | {
      type: "START_RESEARCH_RUN";
      startedAt: string;
      runPassIds: ResearchPassId[];
      preserveExistingSuccesses: boolean;
    }
  | { type: "RESEARCH_PASS_STARTED"; passId: ResearchPassId; attempt: 1 | 2 }
  | {
      type: "RESEARCH_PASS_SUCCESS";
      passId: ResearchPassId;
      findingCount: number;
    }
  | {
      type: "RESEARCH_PASS_FAILED";
      passId: ResearchPassId;
      code: ResearchErrorCode;
      message: string;
    }
  | {
      type: "RESEARCH_RUN_TERMINAL";
      kind: ResearchProgress["kind"];
      failedPassIds: ResearchPassId[];
    }
  | { type: "SET_LLM_STATE"; state: LlmGenerationState }
  | { type: "SET_PRIORITIES_ANSWER"; state: PrioritiesAnswerState }
  | { type: "SET_GENERATED_MEMO"; memo: FollowUpMemo | null }
  | {
      type: "START_GENERATION";
      startedAt: string;
      resumeFromIdx: number;
      excludeSectionIds?: ReadonlyArray<CanonicalSectionId>;
    }
  | { type: "SECTION_STARTED"; sectionId: CanonicalSectionId; attempt: 1 | 2 }
  | { type: "SECTION_SUCCESS"; sectionId: CanonicalSectionId; section: MemoSection }
  | {
      type: "SECTION_FAILED";
      sectionId: CanonicalSectionId;
      code: LlmGenerationErrorCode;
      message: string;
    }
  | { type: "RESET_PROGRESS" }
  | { type: "SET_LLM_PROVIDER_STATUS"; status: LlmStatusResponse | null }
  | { type: "SET_DEMO_MEMO"; memo: FollowUpMemo | null }
  | { type: "SET_GATE_TOKEN_SET"; value: boolean }
  | { type: "START_UNDERSTAND" }
  | {
      type: "SET_UNDERSTANDING";
      understanding: MemoUnderstanding;
      providerMetadata: { providerName: "openai"; modelUsed: string };
      // Phase 6A.3: thread provider warnings (baseline_recovery /
      // baseline_after_timeout / schema_warning) so MemoUnderstandingCard
      // can render the "Recovered from memo text" ribbon.
      warnings?: LlmGenerationWarning[];
    }
  | {
      type: "SET_UNDERSTANDING_ERROR";
      code: MemoUnderstandErrorCode;
      message: string;
    }
  | { type: "SET_SKIP_UNDERSTANDING"; value: boolean }
  | { type: "SET_USER_RESEARCH_PRIORITIES"; value: string }
  | { type: "SET_STALE_CLIENT"; value: boolean }
  | { type: "START_REPORT" }
  | { type: "REPORT_SECTION_STARTED"; id: ResearchReportSectionId; attempt: 1 | 2 }
  | { type: "REPORT_SECTION_SUCCESS"; section: ResearchReportSection }
  | { type: "REPORT_SECTION_FAILED"; id: ResearchReportSectionId; code: ResearchErrorCode }
  | { type: "SET_REPORT_STATE"; state: FullResearchReportState }
  | { type: "RESET" };

function buildInitialProgress(): MemoGenerationProgress {
  return {
    kind: "idle",
    sections: CANONICAL_SECTION_IDS.map<SectionRunState>((id) => ({
      id,
      title: SECTION_TITLES[id],
      status: "pending",
      attempt: 0,
    })),
    completedCount: 0,
  };
}

function buildInitialResearchProgress(): ResearchProgress {
  return {
    kind: "idle",
    passes: RESEARCH_PASS_IDS.map<ResearchPassRunState>((id) => ({
      id,
      title: RESEARCH_PASS_TITLES[id],
      status: "pending",
      attempt: 0,
    })),
    failedPassIds: [],
  };
}

function buildInitialReportProgress(): ResearchReportSectionRunState[] {
  return RESEARCH_REPORT_SECTION_ORDER.map((id) => ({
    id,
    title: RESEARCH_REPORT_SECTION_TITLES[id],
    status: "pending",
    attempt: 0,
  }));
}

const initialState: State = {
  selectedCompany: null,
  initialFile: null,
  extraction: null,
  extractionStatus: "idle",
  dna: null,
  detection: null,
  memoCoverage: null,
  periodOverride: {},
  research: null,
  researchState: { kind: "idle" },
  researchProgress: buildInitialResearchProgress(),
  fullReport: { kind: "idle" },
  fullReportProgress: buildInitialReportProgress(),
  generatedMemo: null,
  llm: { kind: "idle" },
  prioritiesAnswer: { kind: "idle" },
  progress: buildInitialProgress(),
  completedSections: {},
  llmProviderStatus: null,
  demoFollowUpMemo: null,
  gateTokenSet: false,
  understanding: { kind: "idle" },
  skipUnderstanding: false,
  userResearchPriorities: "",
  staleClient: false,
};

function reducer(state: State, action: Action): State {
  switch (action.type) {
    case "SET_SELECTED_COMPANY":
      return {
        ...state,
        selectedCompany: action.company,
        // Mirror the picked name into the period override so the header chip
        // and every downstream company-name lookup reflect it immediately,
        // even before a memo is uploaded.
        periodOverride: {
          ...state.periodOverride,
          detectedCompany: action.company.companyName,
        },
      };
    case "CLEAR_SELECTED_COMPANY":
      return { ...state, selectedCompany: null };
    case "SET_INITIAL_FILE":
      return { ...state, initialFile: action.file };
    case "SET_EXTRACTION_STATUS":
      return { ...state, extractionStatus: action.status };
    case "SET_EXTRACTION":
      return {
        ...state,
        extraction: action.result,
        extractionStatus: action.result.status,
      };
    case "SET_DNA_AND_DETECTION":
      return {
        ...state,
        dna: action.dna,
        detection: action.detection,
        memoCoverage: action.coverage,
        periodOverride: {
          // The user-picked company wins over the heuristic guess; period
          // detection (start month, label) is still trusted and applied.
          detectedCompany:
            state.selectedCompany?.companyName ??
            action.detection.detectedCompany,
          periodLabel: action.detection.best
            ? renderPeriodLabel(action.detection.best)
            : undefined,
          researchStart: action.detection.researchStart,
        },
        research: null,
        researchState: { kind: "idle" },
        researchProgress: buildInitialResearchProgress(),
        fullReport: { kind: "idle" },
        fullReportProgress: buildInitialReportProgress(),
        generatedMemo: null,
        llm: { kind: "idle" },
        progress: buildInitialProgress(),
        completedSections: {},
        // Phase 6A: a new memo invalidates any prior understanding +
        // resets the escape-hatch flag.
        understanding: { kind: "idle" },
        skipUnderstanding: false,
      };
    case "SET_PERIOD_OVERRIDE":
      return {
        ...state,
        periodOverride: { ...state.periodOverride, ...action.override },
      };
    case "SET_RESEARCH_STATE":
      return { ...state, researchState: action.state };
    case "SET_RESEARCH":
      return { ...state, research: action.research };
    case "START_RESEARCH_RUN": {
      const fresh = buildInitialResearchProgress();
      const passes = fresh.passes.map<ResearchPassRunState>((row) => {
        const prev = state.researchProgress.passes.find((p) => p.id === row.id);
        if (
          action.preserveExistingSuccesses &&
          prev &&
          prev.status === "success" &&
          !action.runPassIds.includes(row.id)
        ) {
          return { ...prev, attempt: 0, errorCode: undefined, errorMessage: undefined };
        }
        return row;
      });
      return {
        ...state,
        researchProgress: {
          kind: "running",
          startedAt: action.startedAt,
          passes,
          failedPassIds: [],
        },
      };
    }
    case "RESEARCH_PASS_STARTED": {
      const passes = state.researchProgress.passes.map<ResearchPassRunState>(
        (row) =>
          row.id === action.passId
            ? {
                ...row,
                status: "running",
                attempt: action.attempt,
                errorCode: undefined,
                errorMessage: undefined,
              }
            : row,
      );
      return {
        ...state,
        researchProgress: { ...state.researchProgress, passes },
      };
    }
    case "RESEARCH_PASS_SUCCESS": {
      const passes = state.researchProgress.passes.map<ResearchPassRunState>(
        (row) =>
          row.id === action.passId
            ? { ...row, status: "success", findingCount: action.findingCount }
            : row,
      );
      return {
        ...state,
        researchProgress: { ...state.researchProgress, passes },
      };
    }
    case "RESEARCH_PASS_FAILED": {
      const passes = state.researchProgress.passes.map<ResearchPassRunState>(
        (row) =>
          row.id === action.passId
            ? {
                ...row,
                status: "failed",
                errorCode: action.code,
                errorMessage: action.message,
              }
            : row,
      );
      const failedPassIds = passes
        .filter((p) => p.status === "failed")
        .map((p) => p.id);
      return {
        ...state,
        researchProgress: {
          ...state.researchProgress,
          passes,
          failedPassIds,
        },
      };
    }
    case "RESEARCH_RUN_TERMINAL":
      return {
        ...state,
        researchProgress: {
          ...state.researchProgress,
          kind: action.kind,
          failedPassIds: action.failedPassIds,
        },
      };
    case "SET_LLM_STATE":
      return { ...state, llm: action.state };
    case "SET_PRIORITIES_ANSWER":
      return { ...state, prioritiesAnswer: action.state };
    case "SET_GENERATED_MEMO":
      return { ...state, generatedMemo: action.memo };
    case "START_GENERATION": {
      const fresh = buildInitialProgress();
      const excluded = new Set(action.excludeSectionIds ?? []);
      const sections = fresh.sections.map<SectionRunState>((row, i) => {
        // Sections the orchestrator won't draft are flagged skipped so the UI
        // hides them instead of showing a permanently-pending row.
        const skipped = excluded.has(row.id);
        const prev =
          i < action.resumeFromIdx ? state.progress.sections[i] : undefined;
        if (prev && prev.status === "success") {
          return { ...prev, attempt: 0, errorCode: undefined, errorMessage: undefined, skipped };
        }
        return { ...row, skipped };
      });
      const completedCount = sections.filter((s) => s.status === "success").length;
      return {
        ...state,
        progress: {
          kind: "running",
          startedAt: action.startedAt,
          sections,
          completedCount,
        },
      };
    }
    case "SECTION_STARTED": {
      const sections = state.progress.sections.map<SectionRunState>((row) =>
        row.id === action.sectionId
          ? {
              ...row,
              status: "running",
              attempt: action.attempt,
              errorCode: undefined,
              errorMessage: undefined,
            }
          : row,
      );
      return { ...state, progress: { ...state.progress, sections } };
    }
    case "SECTION_SUCCESS": {
      const sections = state.progress.sections.map<SectionRunState>((row) =>
        row.id === action.sectionId
          ? { ...row, status: "success" }
          : row,
      );
      const completedCount = sections.filter((s) => s.status === "success").length;
      return {
        ...state,
        completedSections: {
          ...state.completedSections,
          [action.sectionId]: action.section,
        },
        progress: {
          ...state.progress,
          sections,
          completedCount,
        },
      };
    }
    case "SECTION_FAILED": {
      const sections = state.progress.sections.map<SectionRunState>((row) =>
        row.id === action.sectionId
          ? {
              ...row,
              status: "failed",
              errorCode: action.code,
              errorMessage: action.message,
            }
          : row,
      );
      return {
        ...state,
        progress: {
          ...state.progress,
          kind: "failed",
          sections,
          failedSectionId: action.sectionId,
        },
      };
    }
    case "RESET_PROGRESS":
      return {
        ...state,
        progress: buildInitialProgress(),
        completedSections: {},
        generatedMemo: null,
        llm: { kind: "idle" },
        prioritiesAnswer: { kind: "idle" },
      };
    case "SET_LLM_PROVIDER_STATUS":
      return { ...state, llmProviderStatus: action.status };
    case "SET_DEMO_MEMO":
      return { ...state, demoFollowUpMemo: action.memo };
    case "SET_GATE_TOKEN_SET":
      return { ...state, gateTokenSet: action.value };
    case "START_UNDERSTAND":
      return { ...state, understanding: { kind: "loading" } };
    case "SET_UNDERSTANDING": {
      // Memo Intelligence is now the AUTHORITATIVE source for memo metadata
      // — it reads the whole document via the LLM, vs. the cheap regex pass
      // that only scans the head. When it gives us a publishedDate, parse
      // it into ISO and overwrite detection.memoWrittenOn so the two UI
      // surfaces can never contradict each other (the user's specific
      // complaint: "No memo date was extracted" vs the Intelligence card
      // showing "DATED 2024-05-07").
      const llmPublishedDate = action.understanding.memo?.publishedDate;
      const llmIso = parseFreeFormDateToIso(llmPublishedDate);
      const detection = state.detection;
      const nextDetection: PeriodDetectionResult | null =
        detection && llmIso
          ? {
              ...detection,
              memoWrittenOn: llmIso,
              memoWrittenOnRaw: llmPublishedDate ?? detection.memoWrittenOnRaw,
              memoWrittenOnConfidence: "high",
              memoWrittenOnReason:
                "extracted by Memo Intelligence (full-document LLM analysis)",
            }
          : detection;
      return {
        ...state,
        detection: nextDetection,
        understanding: {
          kind: "success",
          understanding: action.understanding,
          providerMetadata: action.providerMetadata,
          warnings: action.warnings ?? [],
        },
        // Successful understanding implicitly clears any prior
        // emergency-skip flag — memo-specific research is the
        // expected path again.
        skipUnderstanding: false,
      };
    }
    case "SET_UNDERSTANDING_ERROR":
      return {
        ...state,
        understanding: {
          kind: "error",
          code: action.code,
          message: action.message,
        },
      };
    case "SET_SKIP_UNDERSTANDING":
      return { ...state, skipUnderstanding: action.value };
    case "SET_USER_RESEARCH_PRIORITIES":
      return { ...state, userResearchPriorities: action.value };
    case "SET_STALE_CLIENT":
      return { ...state, staleClient: action.value };
    case "START_REPORT":
      return {
        ...state,
        fullReport: { kind: "loading" },
        fullReportProgress: buildInitialReportProgress(),
      };
    case "REPORT_SECTION_STARTED":
      return {
        ...state,
        fullReportProgress: state.fullReportProgress.map((row) =>
          row.id === action.id
            ? { ...row, status: "running", attempt: action.attempt, errorCode: undefined }
            : row,
        ),
      };
    case "REPORT_SECTION_SUCCESS":
      return {
        ...state,
        fullReportProgress: state.fullReportProgress.map((row) =>
          row.id === action.section.id
            ? { ...row, status: "success", errorCode: undefined }
            : row,
        ),
      };
    case "REPORT_SECTION_FAILED":
      return {
        ...state,
        fullReportProgress: state.fullReportProgress.map((row) =>
          row.id === action.id
            ? { ...row, status: "failed", errorCode: action.code }
            : row,
        ),
      };
    case "SET_REPORT_STATE":
      return { ...state, fullReport: action.state };
    case "RESET":
      return {
        ...initialState,
        // Start over returns to the company picker — clear the prior pick.
        selectedCompany: null,
        progress: buildInitialProgress(),
        researchProgress: buildInitialResearchProgress(),
        llmProviderStatus: state.llmProviderStatus,
        demoFollowUpMemo: state.demoFollowUpMemo,
        gateTokenSet: state.gateTokenSet,
        understanding: { kind: "idle" },
        skipUnderstanding: false,
        userResearchPriorities: "",
        // A stale browser bundle stays stale across "Start over".
        staleClient: state.staleClient,
      };
  }
}

interface MemoProjectContextValue {
  state: State;
  effectiveDetection: {
    detectedCompany: string;
    periodLabel: string;
    researchStart?: string;
    researchCurrent: string;
    assumptionNotes: string[];
  } | null;
  setSelectedCompany: (company: SelectedCompany) => void;
  clearSelectedCompany: () => void;
  extractInitialMemo: (file: File) => Promise<ExtractionResult>;
  setPeriodOverride: (override: PeriodOverride) => void;
  runResearch: () => Promise<void>;
  retryFailedResearchPasses: () => Promise<void>;
  retryAllResearch: () => Promise<void>;
  generateFullResearchReport: () => Promise<void>;
  generateMemo: (withResearch: boolean) => Promise<void>;
  retryFailedSection: () => Promise<void>;
  retryFullMemo: () => Promise<void>;
  refreshLlmProviderStatus: () => Promise<void>;
  syncGateTokenSet: () => void;
  startOver: () => void;
  // Phase 6A
  runMemoUnderstanding: () => Promise<void>;
  rerunMemoUnderstanding: () => Promise<void>;
  skipMemoUnderstanding: () => void;
  // Phase 6C
  setUserResearchPriorities: (value: string) => void;
}

const Ctx = createContext<MemoProjectContextValue | null>(null);

export function MemoProjectProvider({ children }: { children: ReactNode }) {
  const [state, dispatch] = useReducer(reducer, initialState);
  const researchAbort = useRef<AbortController | null>(null);
  const generateAbort = useRef<AbortController | null>(null);
  const understandAbort = useRef<AbortController | null>(null);
  const reportAbort = useRef<AbortController | null>(null);

  useEffect(() => {
    api
      .demoFollowUpMemo()
      .then((memo) => dispatch({ type: "SET_DEMO_MEMO", memo }))
      .catch(() => {});
    api
      .llmStatus()
      .then((status) =>
        dispatch({ type: "SET_LLM_PROVIDER_STATUS", status }),
      )
      .catch(() =>
        dispatch({ type: "SET_LLM_PROVIDER_STATUS", status: null }),
      );
    // Phase 6H: stale-bundle handshake. Compare this bundle's compiled-in
    // build id against the deployed worker's. A mismatch means the tab
    // is running old code against a new worker — surface a reload banner
    // before the user hits a stale_client 400. "dev" (no Vite define,
    // e.g. SSR/tests) never trips it.
    api
      .version()
      .then((v) => {
        if (APP_BUILD_ID !== "dev" && v.buildId !== APP_BUILD_ID) {
          dispatch({ type: "SET_STALE_CLIENT", value: true });
        }
      })
      .catch(() => {});
    dispatch({
      type: "SET_GATE_TOKEN_SET",
      value: Boolean(getLlmGateToken()),
    });
    // Cross-tab gate-token changes:
    const onStorage = (e: StorageEvent): void => {
      if (e.key === GATE_TOKEN_POLL_KEY) {
        dispatch({
          type: "SET_GATE_TOKEN_SET",
          value: Boolean(getLlmGateToken()),
        });
      }
    };
    window.addEventListener("storage", onStorage);
    return () => window.removeEventListener("storage", onStorage);
  }, []);

  const setSelectedCompany = useCallback((company: SelectedCompany): void => {
    dispatch({ type: "SET_SELECTED_COMPANY", company });
  }, []);

  const clearSelectedCompany = useCallback((): void => {
    dispatch({ type: "CLEAR_SELECTED_COMPANY" });
  }, []);

  const extractInitialMemo = useCallback(
    async (file: File): Promise<ExtractionResult> => {
      const ext = getExtension(file.name);
      const local: LocalUploadedFile = {
        id: `local_initial_${Date.now()}`,
        kind: "initial_memo",
        filename: file.name,
        sizeBytes: file.size,
        mime: mimeForFile(file),
        extension: ext,
        uploadedAt: new Date().toISOString(),
        extractionSupported: extractionSupported(ext),
      };
      dispatch({ type: "SET_INITIAL_FILE", file: local });
      dispatch({ type: "SET_EXTRACTION_STATUS", status: "extracting" });
      const result = await extractText(file);
      dispatch({ type: "SET_EXTRACTION", result });
      if (result.status === "success" || result.status === "partial") {
        const dna = buildMemoDnaFromText({
          text: result.text,
          filename: result.source.filename,
        });
        // Period detector finds the memo's TIME ANCHOR (FY26 / Q3 FY25 / …);
        // detectMemoWrittenOn finds the memo's WRITTEN-ON date (the day the
        // author dated it). Both are deterministic regex passes — required
        // before any LLM call so return-period math has a real start date and
        // the period panel can show a confirmable field instead of "fiscal
        // calendar unknown · LOW CONFIDENCE".
        const periodDetection = detectPeriodFromMemoText(result.text);
        const writtenOn = detectMemoWrittenOn(result.text);
        const detection: PeriodDetectionResult = writtenOn
          ? {
              ...periodDetection,
              memoWrittenOn: writtenOn.iso,
              memoWrittenOnRaw: writtenOn.raw,
              memoWrittenOnConfidence: writtenOn.confidence,
              memoWrittenOnReason: writtenOn.reason,
            }
          : periodDetection;
        const coverage = computeMemoCoverage(result.text);
        dispatch({ type: "SET_DNA_AND_DETECTION", dna, detection, coverage });
      }
      return result;
    },
    [],
  );

  const setPeriodOverride = useCallback((override: PeriodOverride) => {
    dispatch({ type: "SET_PERIOD_OVERRIDE", override });
  }, []);

  const refreshLlmProviderStatus = useCallback(async (): Promise<void> => {
    try {
      const status = await api.llmStatus();
      dispatch({ type: "SET_LLM_PROVIDER_STATUS", status });
    } catch {
      dispatch({ type: "SET_LLM_PROVIDER_STATUS", status: null });
    }
  }, []);

  const syncGateTokenSet = useCallback((): void => {
    dispatch({
      type: "SET_GATE_TOKEN_SET",
      value: Boolean(getLlmGateToken()),
    });
  }, []);


  // Phase 6A: Memo Understanding Engine.
  const runMemoUnderstandingOrchestrated = useCallback(async (): Promise<void> => {
    if (!state.dna || !state.extraction || !state.initialFile) return;
    const companyName =
      state.selectedCompany?.companyName ??
      state.periodOverride.detectedCompany ??
      state.detection?.detectedCompany ??
      state.initialFile.filename.replace(/\.[^.]+$/, "");
    const ticker =
      state.selectedCompany?.ticker ?? state.detection?.detectedTicker;
    const detection = state.detection
      ? detectionToResearchDetectionInput(state.detection, companyName)
      : undefined;
    // The picked company is authoritative — don't let the heuristic's
    // detectedCompany leak back in through the detection input.
    if (detection) detection.detectedCompany = companyName;

    understandAbort.current?.abort();
    const controller = new AbortController();
    understandAbort.current = controller;
    dispatch({ type: "START_UNDERSTAND" });

    let response: Awaited<ReturnType<typeof api.memoUnderstand>> | null = null;
    let networkMessage = "";
    try {
      response = await api.memoUnderstand(
        {
          project: {
            id: state.dna.projectId,
            ticker,
            companyName,
            sector: state.selectedCompany?.sector,
          },
          detection,
          memo: {
            id: state.initialFile.id,
            text: state.extraction.text,
            sourceFilename: state.extraction.source.filename,
            sizeBytes: state.extraction.source.sizeBytes,
          },
          dna: state.dna,
        },
        controller.signal,
      );
    } catch (err) {
      networkMessage = err instanceof Error ? err.message : "Network error";
    }
    if (understandAbort.current !== controller) return;
    understandAbort.current = null;

    if (response && response.ok) {
      dispatch({
        type: "SET_UNDERSTANDING",
        understanding: response.understanding,
        providerMetadata: {
          providerName: "openai",
          modelUsed: response.providerMetadata.modelUsed,
        },
        warnings: response.warnings,
      });
      return;
    }
    if (response) {
      dispatch({
        type: "SET_UNDERSTANDING_ERROR",
        code: response.code,
        message: response.message,
      });
      return;
    }
    dispatch({
      type: "SET_UNDERSTANDING_ERROR",
      code: "provider_error",
      message: networkMessage || "Network error",
    });
  }, [
    state.dna,
    state.extraction,
    state.initialFile,
    state.detection,
    state.periodOverride.detectedCompany,
    state.selectedCompany,
  ]);

  const runMemoUnderstanding = useCallback(
    (): Promise<void> => runMemoUnderstandingOrchestrated(),
    [runMemoUnderstandingOrchestrated],
  );
  const rerunMemoUnderstanding = useCallback(
    (): Promise<void> => runMemoUnderstandingOrchestrated(),
    [runMemoUnderstandingOrchestrated],
  );
  const skipMemoUnderstanding = useCallback((): void => {
    dispatch({ type: "SET_SKIP_UNDERSTANDING", value: true });
  }, []);

  const setUserResearchPriorities = useCallback((value: string): void => {
    dispatch({ type: "SET_USER_RESEARCH_PRIORITIES", value });
  }, []);

  // Auto-run memo understanding once DNA + extraction are ready and the
  // provider is configured. Only fires on the idle→loading transition
  // (the dependency check) so subsequent re-renders don't re-trigger.
  const understandKind = state.understanding.kind;
  const llmReadyForUnderstand =
    state.llmProviderStatus?.llmReady === true &&
    state.llmProviderStatus?.researchAvailable === true;
  const understandGateBlocking =
    state.llmProviderStatus?.gateEnabled === true && !state.gateTokenSet;
  useEffect(() => {
    if (understandKind !== "idle") return;
    if (!state.dna || !state.extraction) return;
    if (!llmReadyForUnderstand || understandGateBlocking) return;
    void runMemoUnderstandingOrchestrated();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    understandKind,
    state.dna,
    state.extraction,
    llmReadyForUnderstand,
    understandGateBlocking,
  ]);

  // Stage 1: generate the comprehensive company-wide research report. Runs its
  // own set of web-grounded section calls (independent of the narrowed passes),
  // stores the full report, and is the foundation for the report-driven memo
  // (Stage 2) and Q&A (Stage 3).
  const generateFullResearchReport = useCallback(async (): Promise<void> => {
    if (!state.dna || !state.extraction || !state.initialFile) return;
    const periodLabel =
      state.periodOverride.periodLabel ??
      (state.detection?.best ? renderPeriodLabel(state.detection.best) : "");
    const companyName =
      state.selectedCompany?.companyName ??
      state.periodOverride.detectedCompany ??
      state.detection?.detectedCompany ??
      state.initialFile.filename.replace(/\.[^.]+$/, "");
    const ticker =
      state.selectedCompany?.ticker ?? state.detection?.detectedTicker ?? undefined;

    reportAbort.current?.abort();
    const controller = new AbortController();
    reportAbort.current = controller;

    dispatch({ type: "START_REPORT" });
    // The comprehensive research is now the single research step: it also
    // drives the memo-facing research state (findings assembled from the
    // report sections), so the memo drafter unlocks on success.
    dispatch({ type: "SET_RESEARCH_STATE", state: { kind: "loading" } });

    const memoContext = state.extraction.text?.trim() || undefined;

    const result = await runFullResearchReport({
      project: {
        id: state.dna.projectId,
        companyName,
        ticker,
        sector: state.selectedCompany?.sector,
      },
      companyAliases: {
        longName: companyName,
        aliases: ticker ? [ticker] : undefined,
      },
      detection: {
        periodLabel: periodLabel || "the original memo period",
        researchStart: state.periodOverride.researchStart,
        researchCurrent:
          state.detection?.researchCurrent ??
          new Date().toISOString().slice(0, 7),
        memoWrittenOn: state.detection?.memoWrittenOn,
      },
      memoContext,
      apiCall: (req, signal) => api.researchReportSection(req, signal),
      signal: controller.signal,
      onSectionStart: (id, attempt) =>
        dispatch({ type: "REPORT_SECTION_STARTED", id, attempt }),
      onSectionDone: (section) =>
        dispatch({ type: "REPORT_SECTION_SUCCESS", section }),
      onSectionFail: (id, code) =>
        dispatch({ type: "REPORT_SECTION_FAILED", id, code }),
    });

    if (reportAbort.current !== controller) return;

    if (result.outcome === "aborted") {
      dispatch({ type: "SET_REPORT_STATE", state: { kind: "idle" } });
      dispatch({ type: "SET_RESEARCH_STATE", state: { kind: "idle" } });
    } else if (result.outcome === "failed") {
      dispatch({
        type: "SET_REPORT_STATE",
        state: { kind: "error", code: result.code, message: result.message },
      });
      dispatch({
        type: "SET_RESEARCH_STATE",
        state: { kind: "error", code: result.code, message: result.message },
      });
    } else {
      dispatch({
        type: "SET_REPORT_STATE",
        state: { kind: "success", report: result.report },
      });
      dispatch({ type: "SET_RESEARCH", research: result.research });
      dispatch({
        type: "SET_RESEARCH_STATE",
        state: {
          kind: "success",
          research: result.research,
          providerMetadata: {
            providerName: "openai",
            modelUsed: "gpt-research-report",
          },
          warnings: [],
        },
      });
    }
  }, [
    state.dna,
    state.extraction,
    state.initialFile,
    state.detection,
    state.periodOverride,
    state.selectedCompany,
  ]);

  // The comprehensive report IS the single research step now. These names are
  // kept so existing callers (research button, retries) route to it.
  const runResearch = generateFullResearchReport;
  const retryFailedResearchPasses = generateFullResearchReport;
  const retryAllResearch = generateFullResearchReport;

  const runOrchestratedGeneration = useCallback(
    async (
      withResearch: boolean,
      mode: "fresh" | "resume",
    ): Promise<void> => {
      if (!state.dna || !state.extraction || !state.initialFile) return;
      const companyName =
        state.selectedCompany?.companyName ??
        state.periodOverride.detectedCompany ??
        state.detection?.detectedCompany ??
        state.initialFile.filename.replace(/\.[^.]+$/, "");
      const ticker =
        state.selectedCompany?.ticker ??
        state.detection?.detectedTicker ??
        companyName;
      const periodLabel =
        state.periodOverride.periodLabel ??
        (state.detection?.best ? renderPeriodLabel(state.detection.best) : "");
      const research = withResearch ? state.research : null;

      const failedId =
        mode === "resume" ? state.progress.failedSectionId : undefined;
      const resumeFromIdx =
        mode === "resume" && failedId
          ? Math.max(0, CANONICAL_SECTION_IDS.indexOf(failedId))
          : 0;
      const existingSections =
        mode === "resume" ? state.completedSections : {};

      // Coverage-driven skip list — the user's principle: the follow-up
      // memo should only contain what the original memo actually covered.
      // Sections without a clear analog in the source memo are dropped.
      // Computed BEFORE START_GENERATION so the progress UI never seeds a
      // permanently-pending row for a section we won't draft.
      const coverage = state.memoCoverage;
      const exclude: CanonicalSectionId[] = [];
      // ALWAYS exclude the "Updated Investment View" section. The analyst
      // does not want an AI-generated investment recommendation in any
      // part of the output — the memo presents facts; the human draws the
      // conclusion. (This was sec_investment_action.)
      exclude.push("sec_investment_action");
      if (coverage && !coverage.shareholding) exclude.push("sec_shareholding");
      // The supplementary panels carry the deepest valuation math — keep
      // valuation_detail always on (it's the most-asked-for content), but
      // skip the EPS bridge / forecasts-vs-actuals panels when the memo had
      // no forecasts or valuation framework to anchor them to.
      if (coverage && !coverage.forecasts) exclude.push("sup_eps_bridge");
      if (coverage && !coverage.forecasts) exclude.push("sup_financials_actuals");

      generateAbort.current?.abort();
      const controller = new AbortController();
      generateAbort.current = controller;
      dispatch({
        type: "START_GENERATION",
        startedAt: new Date().toISOString(),
        resumeFromIdx,
        excludeSectionIds: exclude,
      });
      dispatch({ type: "SET_LLM_STATE", state: { kind: "loading" } });

      // Server-fetch the day's live price. If the research orchestrator
      // already injected one into baseDetection, this would normally be
      // redundant — but section generation can be invoked independently
      // (retry, run without prior research), so we always re-fetch. Best
      // effort: null when unavailable, in which case the LLM falls back to
      // its own search rules.
      const livePriceForGen = await fetchCurrentPrice(
        state.selectedCompany,
        controller.signal,
      );
      if (controller.signal.aborted) return;

      const understandingForGen =
        state.understanding.kind === "success"
          ? state.understanding.understanding
          : null;
      const memoUnderstandingDigestForGen = understandingForGen
        ? buildMemoUnderstandingDigest(understandingForGen)
        : undefined;
      // User priorities deliberately NOT threaded into section gen anymore;
      // the dashboard-only PrioritiesAnswer pipeline handles them after
      // the memo completes.

      const result = await runSectionGeneration({
        project: {
          id: state.dna.projectId,
          ticker,
          companyName,
          sector: state.selectedCompany?.sector,
        },
        dna: state.dna,
        excludeSectionIds: exclude,
        detection: periodLabel
          ? {
              detectedCompany: companyName,
              periodLabel,
              researchStart: state.periodOverride.researchStart,
              researchCurrent:
                state.detection?.researchCurrent ??
                new Date().toISOString().slice(0, 7),
              assumptionNotes: state.detection?.assumptionNotes ?? [],
              memoWrittenOn: state.detection?.memoWrittenOn,
              currentPrice: livePriceForGen ?? undefined,
            }
          : undefined,
        research,
        initialMemoId: state.initialFile.id,
        memoUnderstandingDigest: memoUnderstandingDigestForGen,
        apiCall: (req, signal) => api.generateMemoSection(req, signal),
        signal: controller.signal,
        onSectionStart: (sectionId, attempt) => {
          dispatch({ type: "SECTION_STARTED", sectionId, attempt });
        },
        onSectionDone: (sectionId, section) => {
          dispatch({ type: "SECTION_SUCCESS", sectionId, section });
        },
        onSectionFail: () => {
          // SECTION_FAILED dispatch happens after the result resolves so we
          // can also set the LLM error state in lockstep.
        },
        startFromSectionId: failedId,
        existingSections,
      });

      if (generateAbort.current !== controller) return;
      generateAbort.current = null;

      if (result.ok) {
        dispatch({ type: "SET_GENERATED_MEMO", memo: result.memo });
        dispatch({
          type: "SET_LLM_STATE",
          state: {
            kind: "success",
            memo: result.memo,
            providerMetadata: {
              providerName: "openai",
              modelUsed: "gpt-section",
            },
            usedFallback: false,
            warnings: [],
          },
        });
        // Fire the dashboard-only Priorities Q&A pipeline now that the memo
        // is done. Best-effort: a failure here doesn't roll back the memo;
        // the dashboard simply doesn't render the priorities card.
        const priorities = state.userResearchPriorities.trim();
        if (priorities.length > 0) {
          dispatch({ type: "SET_PRIORITIES_ANSWER", state: { kind: "loading" } });
          void api
            .generatePrioritiesAnswer(
              {
                project: {
                  id: state.dna.projectId,
                  ticker,
                  companyName,
                  sector: state.selectedCompany?.sector,
                },
                dna: state.dna,
                detection: periodLabel
                  ? {
                      detectedCompany: companyName,
                      periodLabel,
                      researchStart: state.periodOverride.researchStart,
                      researchCurrent:
                        state.detection?.researchCurrent ??
                        new Date().toISOString().slice(0, 7),
                      assumptionNotes: state.detection?.assumptionNotes ?? [],
                      memoWrittenOn: state.detection?.memoWrittenOn,
                      currentPrice: livePriceForGen ?? undefined,
                    }
                  : undefined,
                research,
                memoUnderstandingDigest: memoUnderstandingDigestForGen,
                userPriorities: priorities,
                initialMemoId: state.initialFile.id,
              },
              controller.signal,
            )
            .then((res) => {
              if (controller.signal.aborted) return;
              if (res.ok) {
                dispatch({
                  type: "SET_PRIORITIES_ANSWER",
                  state: { kind: "success", answer: res.answer },
                });
              } else {
                dispatch({
                  type: "SET_PRIORITIES_ANSWER",
                  state: { kind: "error", code: res.code, message: res.message },
                });
              }
            })
            .catch((err: unknown) => {
              if (controller.signal.aborted) return;
              dispatch({
                type: "SET_PRIORITIES_ANSWER",
                state: {
                  kind: "error",
                  code: "provider_error",
                  message: err instanceof Error ? err.message : "Network error",
                },
              });
            });
        }
        return;
      }

      if (result.code === "aborted") {
        return;
      }

      // Phase 6H: a stale_client signal in the failure means this bundle
      // POSTed an id the deployed worker no longer accepts — flip the
      // reload banner instead of leaving a cryptic provider_error.
      if (result.message.includes("stale_client")) {
        dispatch({ type: "SET_STALE_CLIENT", value: true });
      }

      if (result.failedSectionId) {
        dispatch({
          type: "SECTION_FAILED",
          sectionId: result.failedSectionId,
          code: result.code,
          message: result.message,
        });
      }
      dispatch({
        type: "SET_LLM_STATE",
        state: {
          kind: "error",
          error: `${result.code} · ${result.message}`,
        },
      });
    },
    [
      state.dna,
      state.extraction,
      state.initialFile,
      state.research,
      state.detection,
      state.periodOverride,
      state.progress.failedSectionId,
      state.completedSections,
      state.understanding,
      state.userResearchPriorities,
      state.selectedCompany,
      state.memoCoverage,
    ],
  );

  const generateMemo = useCallback(
    (withResearch: boolean): Promise<void> => {
      dispatch({ type: "RESET_PROGRESS" });
      return runOrchestratedGeneration(withResearch, "fresh");
    },
    [runOrchestratedGeneration],
  );

  const retryFailedSection = useCallback(
    (): Promise<void> =>
      runOrchestratedGeneration(Boolean(state.research), "resume"),
    [runOrchestratedGeneration, state.research],
  );

  const retryFullMemo = useCallback((): Promise<void> => {
    dispatch({ type: "RESET_PROGRESS" });
    return runOrchestratedGeneration(Boolean(state.research), "fresh");
  }, [runOrchestratedGeneration, state.research]);

  const startOver = useCallback(() => {
    researchAbort.current?.abort();
    generateAbort.current?.abort();
    reportAbort.current?.abort();
    researchAbort.current = null;
    generateAbort.current = null;
    reportAbort.current = null;
    dispatch({ type: "RESET" });
  }, []);

  const value = useMemo<MemoProjectContextValue>(() => {
    const effectiveDetection = state.detection
      ? {
          detectedCompany:
            state.periodOverride.detectedCompany ??
            state.detection.detectedCompany ??
            "",
          periodLabel:
            state.periodOverride.periodLabel ??
            (state.detection.best
              ? renderPeriodLabel(state.detection.best)
              : ""),
          researchStart: state.periodOverride.researchStart,
          researchCurrent: state.detection.researchCurrent,
          assumptionNotes: state.detection.assumptionNotes,
        }
      : null;

    return {
      state,
      effectiveDetection,
      setSelectedCompany,
      clearSelectedCompany,
      extractInitialMemo,
      setPeriodOverride,
      runResearch,
      retryFailedResearchPasses,
      retryAllResearch,
      generateFullResearchReport,
      generateMemo,
      retryFailedSection,
      retryFullMemo,
      refreshLlmProviderStatus,
      syncGateTokenSet,
      startOver,
      runMemoUnderstanding,
      rerunMemoUnderstanding,
      skipMemoUnderstanding,
      setUserResearchPriorities,
    };
  }, [
    state,
    setSelectedCompany,
    clearSelectedCompany,
    extractInitialMemo,
    setPeriodOverride,
    runResearch,
    retryFailedResearchPasses,
    retryAllResearch,
    generateFullResearchReport,
    generateMemo,
    retryFailedSection,
    retryFullMemo,
    refreshLlmProviderStatus,
    syncGateTokenSet,
    startOver,
    runMemoUnderstanding,
    rerunMemoUnderstanding,
    skipMemoUnderstanding,
    setUserResearchPriorities,
  ]);

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function useMemoProject(): MemoProjectContextValue {
  const ctx = useContext(Ctx);
  if (!ctx) {
    throw new Error("useMemoProject must be used inside <MemoProjectProvider>");
  }
  return ctx;
}

function renderPeriodLabel(p: {
  kind: string;
  isoDate?: string;
  isoMonth?: string;
  monthLabel?: string;
  quarter?: string;
  fiscalYearLabel?: string;
  rawMatch: string;
}): string {
  switch (p.kind) {
    case "iso_date":
      return p.isoDate ?? p.rawMatch;
    case "month_year":
      return p.monthLabel ?? p.isoMonth ?? p.rawMatch;
    case "quarter_fy":
      return `${p.quarter ?? ""} ${p.fiscalYearLabel ?? ""}`.trim();
    case "fiscal_year":
      return p.fiscalYearLabel ?? p.rawMatch;
    default:
      return p.rawMatch;
  }
}
